version: 0.2
 
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven dependencies..."
      - mvn clean install
 
  build:
    commands:
      - echo "Building the Java app..."
      - mvn package
      - mkdir -p output
      - cp target/*.jar output/
 
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - output/*.jar
  discard-paths: yes
