apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretsanta-deployment
  labels:
    app: secretsanta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretsanta
  template:
    metadata:
      labels:
        app: secretsanta
    spec:
      containers:
        - name: secretsanta
          image: gundrasisudheer/secretsanta:latest
          ports:
            - containerPort: 8080
          # Prometheus annotation for scraping
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 15
          #   periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: secretsanta-service
  labels:
    app: secretsanta
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: NodePort
  selector:
    app: secretsanta
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

